"""Update model with new column

Revision ID: 7d3dee5b1147
Revises: 
Create Date: 2023-10-27 21:22:45.543902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3dee5b1147'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('singal_file_path', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('process_speech_file_path', sa.String(length=30), nullable=True))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('process_speech_file_path')
        batch_op.drop_column('singal_file_path')

    # ### end Alembic commands ###
