"""Update model with new column

Revision ID: 8f4167451773
Revises: 
Create Date: 2023-10-26 12:14:12.727060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4167451773'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_file')
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('singal_file_path', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('process_speech_file_path', sa.String(length=30), nullable=True))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('process_speech_file_path')
        batch_op.drop_column('singal_file_path')

    op.create_table('_alembic_tmp_file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), nullable=False),
    sa.Column('submit_text_file_path', sa.VARCHAR(length=30), nullable=True),
    sa.Column('origin_text_file_path', sa.VARCHAR(length=30), nullable=True),
    sa.Column('modified_text_file_path', sa.VARCHAR(length=30), nullable=True),
    sa.Column('origin_emotion_file_path', sa.VARCHAR(length=30), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('singal_file_path', sa.VARCHAR(length=20), nullable=False),
    sa.Column('process_speech_file_path', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
